export interface Blueprint {
  id: string;
  name: string;
  workbench: 'gunsmith' | 'gear-bench' | 'medical-lab' | 'utility-station' | 'explosives-station' | 'refiner';
  requiredLevel: number;
  type: 'Weapon' | 'Attachment' | 'Shield' | 'Augment' | 'Consumable' | 'Tool' | 'Explosive' | 'Component';
  rarity: 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary';
  priority: 'Essential' | 'High Value' | 'Situational' | 'Low Priority';
  description: string;
  location?: string;
}

export const blueprints: Blueprint[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // GUNSMITH - WEAPONS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'anvil',
    name: 'Anvil Hand Cannon',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Weapon',
    rarity: 'Uncommon',
    priority: 'Essential',
    description: 'High-damage hand cannon with great economy.',
    location: 'Security Lockers, Weapon Cases, Dam Battlegrounds Control Tower',
  },
  {
    id: 'bettina',
    name: 'Bettina AR',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Weapon',
    rarity: 'Epic',
    priority: 'Essential',
    description: 'Top-tier Assault Rifle. Buffed in 1.7.0 (Mag 22, Faster Reload).',
    location: 'Dynamic Security Lockers, High-Value Containers, Night Raids',
  },
  {
    id: 'kettle',
    name: 'Kettle AR',
    workbench: 'gunsmith',
    requiredLevel: 1,
    type: 'Weapon',
    rarity: 'Common',
    priority: 'High Value',
    description: 'Ultra-quiet semi-auto AR. Fire rate capped in 1.11.0 to 450 RPM. TTK increased in 1.17.0.',
    location: 'Common containers, Bird City Map Condition',
  },
  {
    id: 'rattler',
    name: 'Rattler AR',
    workbench: 'gunsmith',
    requiredLevel: 1,
    type: 'Weapon',
    rarity: 'Common',
    priority: 'Essential',
    description: 'Fully automatic assault rifle. Good starter weapon.',
    location: 'Common containers, early quests',
  },
  {
    id: 'renegade',
    name: 'Renegade',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Weapon',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'Lever-action battle rifle. High accuracy and headshot damage.',
    location: 'Security Lockers, Weapon Cases',
  },
  {
    id: 'tempest',
    name: 'Tempest AR',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Weapon',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'Versatile assault rifle, good at all ranges.',
    location: 'Weapon Cases, Blue Gate Reinforced Reception, Security Lockers',
  },
  {
    id: 'osprey',
    name: 'Osprey Sniper',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Weapon',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Long-range precision rifle with high damage.',
    location: 'Security Lockers, Military Containers, Dam Control Tower',
  },
  {
    id: 'vulcano',
    name: 'Vulcano Shotgun',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Weapon',
    rarity: 'Epic',
    priority: 'Situational',
    description: 'Semi-auto shotgun with massive close-range damage.',
    location: 'Security Lockers, Blue Gate Village (requires key)',
  },
  {
    id: 'burletta',
    name: 'Burletta SMG',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Weapon',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'High fire rate SMG with good handling.',
    location: 'Quest reward: Industrial Espionage (Tian Wen, Buried City)',
  },
  {
    id: 'stitcher',
    name: 'Stitcher SMG',
    workbench: 'gunsmith',
    requiredLevel: 1,
    type: 'Weapon',
    rarity: 'Common',
    priority: 'High Value',
    description: 'High rate of fire SMG. Nerfed in 1.17.0 (damage, headshot multiplier, and accuracy).',
    location: 'Common containers, frequently found on other raiders',
  },
  {
    id: 'bobcat',
    name: 'Bobcat Pistol',
    workbench: 'gunsmith',
    requiredLevel: 1,
    type: 'Weapon',
    rarity: 'Common',
    priority: 'Low Priority',
    description: 'Basic starter pistol.',
    location: 'Common containers, early quests',
  },
  {
    id: 'torrente',
    name: 'Torrente LMG',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Weapon',
    rarity: 'Epic',
    priority: 'Situational',
    description: 'Light machine gun with large magazine.',
    location: 'Security Lockers, Military POIs, Harvester Events',
  },
  {
    id: 'venator',
    name: 'Venator Rifle',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Weapon',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Semi-auto marksman rifle. TTK increased in 1.17.0.',
    location: 'Security Lockers, Weapon Cases',
  },
  {
    id: 'aphelion',
    name: 'Aphelion',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Weapon',
    rarity: 'Legendary',
    priority: 'High Value',
    description: 'Legendary Battle Rifle. Fires two-round bursts of high-velocity energy rounds. Buffed handling and maneuverability in 1.17.0.',
    location: 'Stella Montis (Moved in 1.7.0)',
  },
  {
    id: 'il-toro',
    name: 'Il Toro Revolver',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Weapon',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Heavy revolver with high damage per shot.',
    location: 'Security Lockers, Buried City residential areas',
  },
  {
    id: 'hullcracker',
    name: 'Hullcracker Railgun',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Weapon',
    rarity: 'Legendary',
    priority: 'High Value',
    description: 'Devastating railgun requiring Magnetic Accelerator, Heavy Gun Parts, and Exodus Module.',
    location: "Quest reward: The Major's Footlocker (Tian Wen, Dam Battlegrounds)",
  },
  {
    id: 'equalizer',
    name: 'Equalizer',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Weapon',
    rarity: 'Legendary',
    priority: 'High Value',
    description: 'Legendary energy weapon. Requires Magnetic Accelerator, Complex Gun Parts, Queen Reactor.',
    location: 'Harvester Events (guaranteed drop)',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Weapon',
    rarity: 'Legendary',
    priority: 'High Value',
    description: 'Legendary heavy weapon. Same requirements as Equalizer. Buffed handling and maneuverability in 1.17.0.',
    location: 'Harvester Events (guaranteed drop)',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GUNSMITH - ATTACHMENTS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'silencer-2',
    name: 'Silencer II',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Essential',
    description: 'Reduces weapon noise significantly.',
    location: 'Security Lockers, Weapon Cases',
  },
  {
    id: 'silencer-3',
    name: 'Silencer III',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Attachment',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Maximum noise reduction.',
    location: 'Security Lockers (requires Security Breach skill)',
  },
  {
    id: 'compensator-2',
    name: 'Compensator II',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'Reduces weapon recoil.',
    location: 'Weapon Cases, Security Lockers',
  },
  {
    id: 'compensator-3',
    name: 'Compensator III',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Attachment',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Maximum recoil reduction.',
    location: 'Security Lockers (requires Security Breach skill)',
  },
  {
    id: 'extended-medium-mag-2',
    name: 'Extended Medium Magazine II',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'Increases magazine capacity for medium caliber weapons.',
    location: 'Weapon Cases, Security Lockers',
  },
  {
    id: 'extended-medium-mag-3',
    name: 'Extended Medium Magazine III',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Attachment',
    rarity: 'Epic',
    priority: 'Essential',
    description: 'Maximum magazine capacity for ARs.',
    location: 'Security Lockers (requires Security Breach skill)',
  },
  {
    id: 'angled-grip-2',
    name: 'Angled Grip II',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Improves weapon handling.',
    location: 'Weapon Cases, various containers',
  },
  {
    id: 'vertical-grip-2',
    name: 'Vertical Grip II',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Improves recoil control.',
    location: 'Weapon Cases, various containers',
  },
  {
    id: 'stable-stock-2',
    name: 'Stable Stock II',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Improves accuracy when stationary.',
    location: 'Weapon Cases, Security Lockers',
  },
  {
    id: 'extended-barrel',
    name: 'Extended Barrel',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Increases effective range.',
    location: 'Weapon Cases, Security Lockers',
  },
  {
    id: 'shotgun-choke-2',
    name: 'Shotgun Choke II',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Tightens shotgun spread.',
    location: 'Weapon Cases',
  },
  {
    id: 'shotgun-choke-3',
    name: 'Shotgun Choke III',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Attachment',
    rarity: 'Epic',
    priority: 'Situational',
    description: 'Maximum shotgun spread tightening.',
    location: 'Security Lockers (requires Security Breach skill)',
  },
  {
    id: 'silencer-1',
    name: 'Silencer I',
    workbench: 'gunsmith',
    requiredLevel: 1,
    type: 'Attachment',
    rarity: 'Uncommon',
    priority: 'High Value',
    description: 'Basic noise reduction for weapons.',
    location: 'Common containers, Weapon Cases',
  },
  {
    id: 'angled-grip-3',
    name: 'Angled Grip III',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Attachment',
    rarity: 'Epic',
    priority: 'Situational',
    description: 'Maximum weapon handling improvement.',
    location: 'Security Lockers (requires Security Breach skill)',
  },
  {
    id: 'vertical-grip-3',
    name: 'Vertical Grip III',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Attachment',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Maximum recoil control.',
    location: 'Security Lockers (requires Security Breach skill)',
  },
  {
    id: 'stable-stock-3',
    name: 'Stable Stock III',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Attachment',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Maximum accuracy when stationary.',
    location: 'Security Lockers (requires Security Breach skill)',
  },
  {
    id: 'extended-light-mag-2',
    name: 'Extended Light Magazine II',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Increases magazine capacity for light caliber weapons.',
    location: 'Weapon Cases, Security Lockers',
  },
  {
    id: 'extended-light-mag-3',
    name: 'Extended Light Magazine III',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Attachment',
    rarity: 'Epic',
    priority: 'Situational',
    description: 'Maximum magazine capacity for SMGs and pistols.',
    location: 'Security Lockers (requires Security Breach skill)',
  },
  {
    id: 'extended-shotgun-mag-2',
    name: 'Extended Shotgun Magazine II',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Increases shotgun tube capacity.',
    location: 'Weapon Cases, Security Lockers',
  },
  {
    id: 'extended-shotgun-mag-3',
    name: 'Extended Shotgun Magazine III',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Attachment',
    rarity: 'Epic',
    priority: 'Situational',
    description: 'Maximum shotgun tube capacity.',
    location: 'Security Lockers (requires Security Breach skill)',
  },
  {
    id: 'muzzle-brake-2',
    name: 'Muzzle Brake II',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Reduces vertical recoil.',
    location: 'Weapon Cases, Security Lockers',
  },
  {
    id: 'muzzle-brake-3',
    name: 'Muzzle Brake III',
    workbench: 'gunsmith',
    requiredLevel: 3,
    type: 'Attachment',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Maximum vertical recoil reduction.',
    location: 'Security Lockers (requires Security Breach skill)',
  },
  {
    id: 'shotgun-silencer',
    name: 'Shotgun Silencer',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Reduces shotgun noise significantly.',
    location: 'Weapon Cases, Security Lockers',
  },
  {
    id: 'padded-stock',
    name: 'Padded Stock',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Low Priority',
    description: 'Reduces weapon sway and improves ADS stability.',
    location: 'Weapon Cases, various containers',
  },
  {
    id: 'lightweight-stock',
    name: 'Lightweight Stock',
    workbench: 'gunsmith',
    requiredLevel: 2,
    type: 'Attachment',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Reduces weapon weight and improves ADS speed.',
    location: 'Weapon Cases, various containers',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GEAR BENCH
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'shield-medium',
    name: 'Medium Shield',
    workbench: 'gear-bench',
    requiredLevel: 2,
    type: 'Shield',
    rarity: 'Rare',
    priority: 'Essential',
    description: 'Balanced protection and mobility.',
    location: 'Gear Bench craft, various containers',
  },
  {
    id: 'shield-heavy',
    name: 'Heavy Shield',
    workbench: 'gear-bench',
    requiredLevel: 3,
    type: 'Shield',
    rarity: 'Epic',
    priority: 'Essential',
    description: 'Maximum protection, slower recharge.',
    location: 'Gear Bench craft, Security Lockers',
  },
  {
    id: 'combat-mk3-aggressive',
    name: 'Combat Mk.3 (Aggressive)',
    workbench: 'gear-bench',
    requiredLevel: 3,
    type: 'Augment',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Damage-focused combat augment.',
    location: 'Blue Gate Reinforced Reception, Security Lockers',
  },
  {
    id: 'combat-mk3-flanking',
    name: 'Combat Mk.3 (Flanking)',
    workbench: 'gear-bench',
    requiredLevel: 3,
    type: 'Augment',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Movement-focused combat augment.',
    location: 'Blue Gate Reinforced Reception, Security Lockers',
  },
  {
    id: 'looting-mk3',
    name: 'Looting Mk.3 (Survivor)',
    workbench: 'gear-bench',
    requiredLevel: 3,
    type: 'Augment',
    rarity: 'Epic',
    priority: 'Essential',
    description: 'Greatly increases loot detection and highlights items through walls.',
    location: 'Security Lockers, Buried City Pharmacy',
  },
  {
    id: 'looting-mk3-safekeeper',
    name: 'Looting Mk.3 (Safekeeper)',
    workbench: 'gear-bench',
    requiredLevel: 3,
    type: 'Augment',
    rarity: 'Epic',
    priority: 'Essential',
    description: '18 item slots, Heavy Shield compatible. Features a "Safe Pocket" that protects any item from loss upon death.',
    location: 'High Loot Zones during Major Map Conditions',
  },
  {
    id: 'tactical-mk3-revival',
    name: 'Tactical Mk.3 (Revival)',
    workbench: 'gear-bench',
    requiredLevel: 3,
    type: 'Augment',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Integrated Defibrillator for free revives (4m CD) and passive health regen.',
    location: 'High Loot Zones during Major Map Conditions, Surgeon Raider Deck reward',
  },
  {
    id: 'tactical-mk3-defensive',
    name: 'Tactical Mk.3 (Defensive)',
    workbench: 'gear-bench',
    requiredLevel: 3,
    type: 'Augment',
    rarity: 'Epic',
    priority: 'Situational',
    description: 'Defense-focused tactical augment.',
    location: 'Security Lockers, Military POIs',
  },
  {
    id: 'tactical-mk3-healing',
    name: 'Tactical Mk.3 (Healing)',
    workbench: 'gear-bench',
    requiredLevel: 3,
    type: 'Augment',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Healing-focused tactical augment.',
    location: 'Security Lockers, Medical POIs',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MEDICAL LAB
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'vita-spray',
    name: 'Vita Spray',
    workbench: 'medical-lab',
    requiredLevel: 3,
    type: 'Consumable',
    rarity: 'Epic',
    priority: 'Essential',
    description: 'Rapid healing spray with multiple uses.',
    location: 'Medical Lab craft, Medical containers',
  },
  {
    id: 'vita-shot',
    name: 'Vita Shot',
    workbench: 'medical-lab',
    requiredLevel: 2,
    type: 'Consumable',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'Single-use healing injection.',
    location: 'Medical Lab craft, Medical containers',
  },
  {
    id: 'defibrillator',
    name: 'Defibrillator',
    workbench: 'medical-lab',
    requiredLevel: 3,
    type: 'Tool',
    rarity: 'Epic',
    priority: 'Situational',
    description: 'Revives downed teammates faster.',
    location: 'Medical Lab craft, Medical POIs',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UTILITY STATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'light-stick',
    name: 'Light Stick',
    workbench: 'utility-station',
    requiredLevel: 1,
    type: 'Tool',
    rarity: 'Common',
    priority: 'Situational',
    description: 'Illuminates dark areas.',
    location: 'Buried City Pharmacy, Blue Gate underground',
  },
  {
    id: 'barricade-kit',
    name: 'Barricade Kit',
    workbench: 'utility-station',
    requiredLevel: 2,
    type: 'Tool',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Deploys temporary cover.',
    location: 'Utility containers, Security areas',
  },
  {
    id: 'snap-hook',
    name: 'Snap Hook',
    workbench: 'utility-station',
    requiredLevel: 2,
    type: 'Tool',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'Allows quick rappelling down cliffs.',
    location: 'Utility containers, various POIs',
  },
  {
    id: 'smoke-grenade',
    name: 'Smoke Grenade',
    workbench: 'utility-station',
    requiredLevel: 2,
    type: 'Tool',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'Creates smoke cover for escapes.',
    location: 'Utility containers, various POIs',
  },
  {
    id: 'seeker-grenade',
    name: 'Seeker Grenade',
    workbench: 'utility-station',
    requiredLevel: 2,
    type: 'Tool',
    rarity: 'Rare',
    priority: 'Essential',
    description: 'Homing grenade that targets and disables airborne ARC threats.',
    location: 'Security Lockers, Reward for Shared Watch event',
  },
  {
    id: 'tagging-grenade',
    name: 'Tagging Grenade',
    workbench: 'utility-station',
    requiredLevel: 2,
    type: 'Tool',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Marks enemies in an area.',
    location: 'Utility containers',
  },
  {
    id: 'remote-raider-flare',
    name: 'Remote Raider Flare',
    workbench: 'utility-station',
    requiredLevel: 2,
    type: 'Tool',
    rarity: 'Rare',
    priority: 'Low Priority',
    description: 'Signals extraction point.',
    location: 'Utility containers',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EXPLOSIVES STATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'trigger-nade',
    name: "Trigger 'Nade",
    workbench: 'explosives-station',
    requiredLevel: 2,
    type: 'Explosive',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'Remote-detonated grenade.',
    location: 'Quest reward: Sparks Fly (Apollo, any map)',
  },
  {
    id: 'lure-grenade',
    name: 'Lure Grenade',
    workbench: 'explosives-station',
    requiredLevel: 2,
    type: 'Explosive',
    rarity: 'Rare',
    priority: 'Essential',
    description: 'Attracts ARC enemies to a location.',
    location: 'Quest reward: Greasing Her Palms (Celeste, multiple maps)',
  },
  {
    id: 'trailblazer-grenade',
    name: 'Trailblazer Grenade',
    workbench: 'explosives-station',
    requiredLevel: 2,
    type: 'Explosive',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'Emits a trail of flammable gas that ignites for an explosive chain reaction.',
    location: 'Security Lockers, Industrial POIs',
  },
  {
    id: 'showstopper',
    name: 'Showstopper',
    workbench: 'explosives-station',
    requiredLevel: 3,
    type: 'Explosive',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'High-damage explosive grenade.',
    location: 'Blue Gate Reinforced Reception, Security Lockers',
  },
  {
    id: 'blaze-grenade',
    name: 'Blaze Grenade',
    workbench: 'explosives-station',
    requiredLevel: 2,
    type: 'Explosive',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Creates area of fire damage.',
    location: 'Explosives containers, various POIs',
  },
  {
    id: 'explosive-mine',
    name: 'Explosive Mine',
    workbench: 'explosives-station',
    requiredLevel: 2,
    type: 'Explosive',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Proximity-triggered explosive.',
    location: 'Explosives containers, Military POIs',
  },
  {
    id: 'jolt-mine',
    name: 'Jolt Mine',
    workbench: 'explosives-station',
    requiredLevel: 2,
    type: 'Explosive',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Stuns enemies in radius.',
    location: 'Explosives containers, various POIs',
  },
  {
    id: 'gas-mine',
    name: 'Gas Mine',
    workbench: 'explosives-station',
    requiredLevel: 2,
    type: 'Explosive',
    rarity: 'Rare',
    priority: 'Situational',
    description: 'Releases toxic gas cloud when triggered.',
    location: 'Explosives containers, Industrial POIs',
  },
  {
    id: 'pulse-mine',
    name: 'Pulse Mine',
    workbench: 'explosives-station',
    requiredLevel: 2,
    type: 'Explosive',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'EMP mine that disables ARC enemies temporarily.',
    location: 'Explosives containers, Military POIs',
  },
  {
    id: 'wolfpack',
    name: 'Wolfpack',
    workbench: 'explosives-station',
    requiredLevel: 3,
    type: 'Explosive',
    rarity: 'Epic',
    priority: 'Situational',
    description: 'Multi-rocket launcher explosive. Requires Rocketeer Driver to craft (added in 1.17.0).',
    location: 'Security Lockers, Harvester Events',
  },
  {
    id: 'deadline',
    name: 'Deadline Mine',
    workbench: 'explosives-station',
    requiredLevel: 3,
    type: 'Explosive',
    rarity: 'Epic',
    priority: 'High Value',
    description: 'Timed mine with massive 1,000 damage in a 10m radius. Requires Comet Igniter to craft. Added in Shrouded Sky 1.17.0.',
    location: 'Industrial Containers, Apollo trader, garages and industrial underpasses',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // REFINER - COMPONENTS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'light-gun-parts',
    name: 'Light Gun Parts',
    workbench: 'refiner',
    requiredLevel: 1,
    type: 'Component',
    rarity: 'Common',
    priority: 'Essential',
    description: 'Crafted from Metal Parts.',
    location: 'Refiner craft',
  },
  {
    id: 'medium-gun-parts',
    name: 'Medium Gun Parts',
    workbench: 'refiner',
    requiredLevel: 2,
    type: 'Component',
    rarity: 'Uncommon',
    priority: 'Essential',
    description: 'Crafted from Metal Parts + ARC Powercell.',
    location: 'Refiner craft, Bombardier/Bastion enemies',
  },
  {
    id: 'heavy-gun-parts',
    name: 'Heavy Gun Parts',
    workbench: 'refiner',
    requiredLevel: 3,
    type: 'Component',
    rarity: 'Rare',
    priority: 'High Value',
    description: 'Crafted from advanced materials.',
    location: 'Refiner craft, Rocketeer enemies',
  },
  {
    id: 'complex-gun-parts',
    name: 'Complex Gun Parts',
    workbench: 'refiner',
    requiredLevel: 3,
    type: 'Component',
    rarity: 'Epic',
    priority: 'Essential',
    description: 'Required for legendary weapons.',
    location: 'Refiner craft from advanced ARC materials',
  },
  {
    id: 'mechanical-components',
    name: 'Mechanical Components',
    workbench: 'refiner',
    requiredLevel: 2,
    type: 'Component',
    rarity: 'Uncommon',
    priority: 'Essential',
    description: 'Crafted from 5 Metal Parts + ARC Powercell.',
    location: 'Refiner craft',
  },
  {
    id: 'electrical-components',
    name: 'Electrical Components',
    workbench: 'refiner',
    requiredLevel: 2,
    type: 'Component',
    rarity: 'Rare',
    priority: 'Essential',
    description: 'Required for gear and utility crafting.',
    location: 'Refiner craft, recycle electronics',
  }
];

export const getBlueprintsByWorkbench = (workbench: Blueprint['workbench']) => {
  return blueprints.filter(bp => bp.workbench === workbench);
};

export const getBlueprintsByPriority = (priority: Blueprint['priority']) => {
  return blueprints.filter(bp => bp.priority === priority);
};

export const getCollectionStats = (ownedIds: string[]) => {
  const total = blueprints.length;
  const owned = ownedIds.length;
  const essential = blueprints.filter(bp => bp.priority === 'Essential');
  const essentialOwned = essential.filter(bp => ownedIds.includes(bp.id)).length;

  const byWorkbench: Record<string, { total: number; owned: number }> = {};
  blueprints.forEach(bp => {
    if (!byWorkbench[bp.workbench]) {
      byWorkbench[bp.workbench] = { total: 0, owned: 0 };
    }
    byWorkbench[bp.workbench].total++;
    if (ownedIds.includes(bp.id)) {
      byWorkbench[bp.workbench].owned++;
    }
  });

  return { total, owned, essentialTotal: essential.length, essentialOwned, byWorkbench };
};
